# DigitalOcean App Spec
name: whatsapp-automation-console
region: nyc
services:
- dockerfile_path: Dockerfile
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-s-1vcpu-1gb
  name: whatsapp-web-service
  source_dir: /
  github:
    branch: master
    deploy_on_push: true
    repo: FASIL2526/whatsapp_bulk_msg
  envs:
  - key: AUTH_SECRET
    scope: RUN_AND_BUILD_TIME
    value: restartx-secure-secret-123
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "3000"
  # This section helps force DigitalOcean to recognize the Dockerfile
  build_command: ""
