const DEFAULT_CONFIG = {
  HEADLESS: "true",
  RECIPIENTS: "",
  STARTUP_MESSAGE: "Automation is live.",
  BULK_SEND_MODE: "instant",
  BULK_DELAY_MS: "1500",
  BULK_RANDOM_MIN_MS: "700",
  BULK_RANDOM_MAX_MS: "2500",
  BULK_TEMPLATE_MODE: "single",
  BULK_TEMPLATE_LINES: "",
  AUTO_REPLY_ENABLED: "true",
  AUTO_REPLY_MODE: "exact",
  AUTO_REPLY_TRIGGER: "hi",
  AUTO_REPLY_TEXT: "Hello! This is an auto-reply.",
  AUTO_REPLY_RULES: "",
  SCHEDULE_ENABLED: "false",
  SCHEDULE_CRON: "0 9 * * *",
  SCHEDULE_MESSAGE: "Daily reminder",
  AI_SALES_ENABLED: "false",
  AI_PROVIDER: "google",
  AI_MODEL: "gemini-1.5-flash",
  AI_SALES_SCOPE: "not_matched",
  AI_SALES_GROUPS: "false",
  AI_BOOKING_ENABLED: "false",
  AI_BOOKING_LINK: "",
  AI_API_KEY: "",
  AI_PRODUCT_KNOWLEDGE: "Our product is a premium WhatsApp automation tool that helps businesses scale their communication.",
  AI_MEMORY_TURNS: "10",
  AI_QUALIFICATION_ENABLED: "true",
  AI_QUALIFICATION_FIELDS: "need,budget,timeline,decision-maker",
  AI_CLOSING_FLOW: "balanced",
  AI_CLOSE_QUESTION_MODE: "hot_only",
  AI_AUTO_STORY_TO_CLOSE: "false",
  AI_CLOSING_STORY: "One client moved from slow manual replies to booked demos in 10 days after switching to this workflow.",
  AI_WHATSAPP_STATUS_FEATURES: "false",
  AI_WHATSAPP_STATUS_FEATURES_TEXT: "We also support WhatsApp Status features so you can post offers/updates and attract inbound leads.",
  AI_STATUS_AUTOPILOT_ENABLED: "false",
  AI_STATUS_AUTOPILOT_CRON: "0 */6 * * *",
  AI_STATUS_AUTOPILOT_TONE: "direct",
  AI_STATUS_AUTOPILOT_CTA: "Reply 'START' to get full details.",
  AI_STATUS_AUTOPILOT_USE_AI: "true",
  AI_OBJECTION_PLAYBOOK: "",
  AI_FOLLOW_UP_ENABLED: "false",
  AI_FOLLOW_UP_DELAY_MINUTES: "180",
  AI_FOLLOW_UP_MAX_ATTEMPTS: "3",
  AI_FOLLOW_UP_TEMPLATE: "Quick follow-up: still interested in solving this now?",

  // ─── Autonomous features ───────────────────────────────────────────────
  NURTURE_DRIP_ENABLED: "false",
  NURTURE_DRIP_STEPS: "",
  AUTO_REENGAGE_ENABLED: "false",
  AUTO_REENGAGE_STALE_DAYS: "3",
  AUTO_REENGAGE_MAX_ATTEMPTS: "2",
  AUTO_ESCALATION_ENABLED: "false",
  AUTO_ESCALATION_OPERATOR: "",
  AUTO_LEAD_ROUTING_ENABLED: "false",
  AB_TEST_ENABLED: "false",
  AB_TEST_MIN_SENDS: "30",
  AUTO_DAILY_DIGEST_ENABLED: "false",
  AUTO_DAILY_DIGEST_OPERATOR: "",
  AUTO_DAILY_DIGEST_HOUR: "9",
  AUTO_OBJECTION_ENABLED: "false",
  AUTO_CLEANUP_ENABLED: "false",
  AUTO_CLEANUP_STALE_DAYS: "30",
  AUTO_TIMEZONE_ENABLED: "false",
  AUTO_TAGGING_ENABLED: "false",

  // ─── Agentic features (v2) ──────────────────────────────────────────────
  OUTBOUND_PROSPECTING_ENABLED: "false",
  OUTBOUND_MAX_DAILY: "20",
  OUTBOUND_COOLDOWN_HOURS: "6",
  OUTBOUND_TEMPLATE: "",
  GOAL_PLANNER_ENABLED: "false",
  GOAL_TYPE: "bookings",
  GOAL_WEEKLY_TARGET: "5",
  PROMPT_TUNING_ENABLED: "false",
  OFFER_AUTHORITY_ENABLED: "false",
  OFFER_MAX_DISCOUNT_PCT: "15",
  OFFER_MIN_LEAD_SCORE: "60",
  OFFER_BASE_PRICE: "0",
  OFFER_CURRENCY: "USD",
  OFFER_ALLOW_PAYMENT_PLAN: "false",
  OFFER_MAX_PER_LEAD: "2",
  OFFER_URGENCY_WINDOW: "48 hours",
  SELF_HEALING_ENABLED: "false",

  // ─── WhatsApp Alerts & Auto-Reports ─────────────────────────────────────
  WHATSAPP_ALERTS_ENABLED: "false",
  WHATSAPP_ALERTS_OPERATOR: "",
  WHATSAPP_ALERTS_EVENTS: "new_lead,hot_lead,human_requested,booking_confirmed,escalation,closed_won,ai_error,daily_report",
  WHATSAPP_ALERTS_REPORT_INTERVAL_HRS: "1",

  // ─── Human Takeover ──────────────────────────────────────────────────
  HUMAN_TAKEOVER_TIMEOUT_HRS: "2",
};

module.exports = {
  DEFAULT_CONFIG,
};
