const DEFAULT_CONFIG = {
  HEADLESS: "true",
  RECIPIENTS: "",
  STARTUP_MESSAGE: "Automation is live.",
  BULK_SEND_MODE: "instant",
  BULK_DELAY_MS: "1500",
  BULK_RANDOM_MIN_MS: "700",
  BULK_RANDOM_MAX_MS: "2500",
  BULK_TEMPLATE_MODE: "single",
  BULK_TEMPLATE_LINES: "",
  AUTO_REPLY_ENABLED: "true",
  AUTO_REPLY_MODE: "exact",
  AUTO_REPLY_TRIGGER: "hi",
  AUTO_REPLY_TEXT: "Hello! This is an auto-reply.",
  AUTO_REPLY_RULES: "",
  SCHEDULE_ENABLED: "false",
  SCHEDULE_CRON: "0 9 * * *",
  SCHEDULE_MESSAGE: "Daily reminder",
  AI_SALES_ENABLED: "false",
  AI_PROVIDER: "google",
  AI_MODEL: "gemini-1.5-flash",
  AI_SALES_SCOPE: "not_matched",
  AI_SALES_GROUPS: "false",
  AI_BOOKING_ENABLED: "false",
  AI_BOOKING_LINK: "",
  AI_API_KEY: "",
  AI_PRODUCT_KNOWLEDGE: "Our product is a premium WhatsApp automation tool that helps businesses scale their communication.",
  AI_MEMORY_TURNS: "10",
  AI_QUALIFICATION_ENABLED: "true",
  AI_QUALIFICATION_FIELDS: "need,budget,timeline,decision-maker",
  AI_CLOSING_FLOW: "balanced",
  AI_CLOSE_QUESTION_MODE: "hot_only",
  AI_AUTO_STORY_TO_CLOSE: "false",
  AI_CLOSING_STORY: "One client moved from slow manual replies to booked demos in 10 days after switching to this workflow.",
  AI_WHATSAPP_STATUS_FEATURES: "false",
  AI_WHATSAPP_STATUS_FEATURES_TEXT: "We also support WhatsApp Status features so you can post offers/updates and attract inbound leads.",
  AI_STATUS_AUTOPILOT_ENABLED: "false",
  AI_STATUS_AUTOPILOT_CRON: "0 */6 * * *",
  AI_STATUS_AUTOPILOT_TONE: "direct",
  AI_STATUS_AUTOPILOT_CTA: "Reply 'START' to get full details.",
  AI_STATUS_AUTOPILOT_USE_AI: "true",
  AI_OBJECTION_PLAYBOOK: "",
  AI_FOLLOW_UP_ENABLED: "false",
  AI_FOLLOW_UP_DELAY_MINUTES: "180",
  AI_FOLLOW_UP_MAX_ATTEMPTS: "3",
  AI_FOLLOW_UP_TEMPLATE: "Quick follow-up: still interested in solving this now?",
};

module.exports = {
  DEFAULT_CONFIG,
};
